services:
  my-site:
    build: .
    container_name: my-site
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.my-site.rule=Host(`staging.jacobamrine.com`)
      - traefik.http.routers.my-site.entrypoints=websecure
      - traefik.http.routers.my-site.tls=true
      - traefik.http.routers.my-site.tls.certresolver=le
      - traefik.http.services.my-site.loadbalancer.server.port=80
    networks:
      - proxy

networks:
  proxy:
    external: true